Samples:
    10X_P4_3_S1_L001
    # sample IDs

# STAR generated index folder
STAR_IND: /fs/cbsuvlaminck/workdir/fw262/denovoAssembly/STAR_indices/GRCm38_gencode.vM21

DATADIR: data # directory where raw fastq files are stored
PIPELINE_MAJOR: results_out # folder where scRNA-seq expression matrices are going to be stored

GLOBAL:
    allowed_mismatch: 10 # outFilterMismatchNmax parameter for STAR alignment
    BC_range: # barcode range
        first: 1
        last: 16
        length: 16
    UMI_range: # unique molecular identifier range
        first: 17
        last: 28 # 28 for v3, up to 26 for v2
        length: 10
    total_length: 26

# list of program locations
STAREXEC: /programs/STAR-2.7.9a/bin/Linux_x86_64/STAR # path to STAR 
KRAKEN: /programs/kraken2.09/kraken2 # path to Kraken2
KRAKEN_DB: /fs/cbsuvlaminck3/workdir/fw262/denovoAssembly/Kraken/standardDB # Kraken database location

CORES: 5 # how many cores to give for each process, snakemake automatically parallelize process using "snakemake -j {numTotalCores}"
